#
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
# ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝

# -*- List of preload wallpapers -*-
preload = ~/wallpapers/a.png
preload = ~/wallpapers/b.png
preload = ~/wallpapers/c.png
preload = ~/wallpapers/d.png
preload = ~/wallpapers/e.png
preload = ~/wallpapers/f.png
preload = ~/wallpapers/g.png
preload = ~/wallpapers/h.png
preload = ~/wallpapers/i.png

# -*- Wallpapers -*-
wallpaper = eDP-1,~/wallpapers/a.png
fade = true
